### ISSUE TITLE
macos cannot load libcedar_java_ffi.dylib

### ISSUE THREAD

**Issue by jazzyMix** [cedar-policy/cedar-java#23]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

While following the guide to run ./gradlew build under cedar-java-hello-world, I run into this error 
  SampleJavaClassTest > testFailing() FAILED
    java.lang.UnsatisfiedLinkError: Can't load library: /Users/deck/git/cedar-examples/cedar-java/CedarJavaFFI/target/debug/libcedar_java_ffi.dylib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at cedarpolicy.WrapperAuthorizationEngine.<clinit>(WrapperAuthorizationEngine.java:44)
        at samplelib.SampleJavaClass.shouldFail(SampleJavaClass.java:93)
        at samplelib.SampleJavaClassTest.testFailing(SampleJavaClassTest.java:45)

SampleJavaClassTest > sampleMethodTest() FAILED
    java.lang.NoClassDefFoundError: Could not initialize class cedarpolicy.WrapperAuthorizationEngine
        at samplelib.SampleJavaClass.sampleMethod(SampleJavaClass.java:41)
        at samplelib.SampleJavaClassTest.sampleMethodTest(SampleJavaClassTest.java:35)

2 tests completed, 2 failed

I have follow the guideline to build the libcedar_java_ffi.dylib file but I cannot let java to load it successfully 

This works on my windows machine though, but not on my mac running m1 chip

### Expected behavior

test should pass 

### Reproduction steps

under /cedar-java-hello-world

run 
cd cedar-java/CedarJavaFFI && cargo build
cd ../../cedar-java-hello-world && ./gradlew build

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

### Operating  System

macos running m1 chip

**Comment by andrewmwells-amazon** [comment]
Hmm, I have tested this on an Intel Mac and it works for me. Just to check, you are setting your `CEDAR_JAVA_FFI_LIB` variable?

**Comment by jazzyMix** [comment]
Yeah I know it is probably something wrong on my side but I wanna confirm with you.

I end up changing the jdk to correcto and it end up working for me, since i assume that is the jdk you are probably using.
Thanks, closing the issue.

**Comment by andrewmwells-amazon** [comment]
>I end up changing the jdk to correcto and it end up working for me, since i assume that is the jdk you are probably using.
Thanks, closing the issue.
Interesting. Yes, I'm using Corretto on Mac (though I've tested with OpenJDK on Ubuntu). Do you mind sharing which JDK you were using before so I can try to reproduce the issue?

**Comment by jazzyMix** [comment]
this is my previous jdk 
  17.0.4 (x86_64) "Eclipse Adoptium" - "OpenJDK 17.0.4" /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home

**Comment by jazzyMix** [comment]
oh looks like my old jdk has been x86 the whole time, sorry for the trouble

**Comment by himanshupandey-cpi** [comment]
@jazzyMix I am also facing the same issue, wondering this JDK did you use to fix this. Can you please share which JDK is working for you.

**Comment by jazzyMix** [comment]
@himanshupandey-cpi  i used the amazon corretto https://docs.aws.amazon.com/corretto/latest/corretto-17-ug/downloads-list.html , my mistake is I used the x86 sdk for my arm mac
